name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls
            cd ${{ secrets.SERVER_PULL_DIR }}
            git checkout .
            git pull origin main
            cp homev3.sk ${{ secrets.SERVER_DEPLOY_DIR }}
            cp HomeV3/homev3-main.sk ${{ secrets.SERVER_DEPLOY_DIR }}/homeV3
            cp HomeV3/homev3-functions.sk ${{ secrets.SERVER_DEPLOY_DIR }}/homeV3
            cp HomeV3/homev3-main.sk ${{ secrets.SERVER_DEPLOY_DIR }}/homeV3
